# frozen_string_literal: true

# The Stars & Garters "Standard 2026" Residency Agreement, as a ContractTemplate
# body (ActionText HTML). Almost the entire document is fixed boilerplate — the
# only per-contract values are:
#   * {{current_date}}      — stands in for the Effective Date
#   * {{contractor_name}}   — the Producer
#   * {{license_schedule}}  — the Section 1.1 dates/stage/rent grid, generated
#                             per contract from its bookings (see Contract).
#   * {{services}}          — the service line items, if any (renders nothing when
#                             the contract has no services).
#
# Because the body carries {{license_schedule}} inline, the system does NOT append
# the automatic "Deal Terms" schedule (Contract#render_document_for). Signatures
# are appended by ContractPdf, so this body deliberately ends before them.
#
# Seed/refresh it for an organization with:
#   bin/rails "contract_templates:seed_residency[ORG_ID]"
module StarsAndGartersResidencyTemplate
  TEMPLATE_NAME = "Stars & Garters Residency Agreement (Standard 2026)"

  CONTENT = <<~HTML.strip
    <div><strong>STARS &amp; GARTERS RESIDENCY AGREEMENT</strong></div>
    <div>(Production Performance Space and Designated Ancillary and Support Spaces Only)</div>
    <div><br></div>
    <div>This Rental Agreement (the &ldquo;Agreement&rdquo;) is made as of {{current_date}} (the &ldquo;Effective Date&rdquo;) by and between Stars &amp; Garters (the &ldquo;Licensor&rdquo;), with venue space at 3914 N Clark St, Chicago, IL 60613 and {{contractor_name}} (the &ldquo;Producer&rdquo;) and its representatives for select dates in 2026.</div>
    <div><br></div>
    <div><strong>RECITALS</strong></div>
    <div><br></div>
    <div>WHEREAS, Licensor operates Stars &amp; Garters, a theatrical performance space with two performance spaces (The Mainstage / 80 seats &amp; The Rouge Room 40 seats) offering for the production of live stage performances (&ldquo;Theater&rdquo;) in the building located at 3914 N Clark Street, Chicago, IL (the &ldquo;Building&rdquo;). Producer will offer the Production to the general public on a commercial basis and desires to obtain a license from Licensor for the use of the theater; and</div>
    <div><br></div>
    <div>WHEREAS, Licensor and Producer wish to enter into this Agreement, and arrange for the commercial use of the Theater for the Production, on the terms and conditions set forth herein.</div>
    <div><br></div>
    <div>NOW, THEREFORE, in consideration of the mutual promises, covenants and agreements contained in this Agreement, and other good and valuable consideration, the receipt and sufficiency of which is hereby acknowledged, the parties, intending to be legally bound, hereby agree as follows:</div>
    <div><br></div>
    <div><strong>AGREEMENT</strong></div>
    <div><br></div>
    <div><strong>1. LICENSE PERIOD AND FEES</strong></div>
    <div><br></div>
    <div><strong>1.1 License Period and Fees:</strong> Use of the Main Stage/Rouge Room space on the following dates. In the case of residence agreements, will be reviewed after 6 months for viability for both parties and term if not extended to be 12 months. Dates in red indicate possible extension dates.</div>
    <div><br></div>
    {{license_schedule}}
    <div><br></div>
    <div><strong>1.2 PAYMENT.</strong> Licensor will provide space at agreed upon time. Space will be made available to Producer 30 minutes prior to show start. Licensor will make all reasonable attempt to aid producer in set up process. Licensor will, if requested in advance, allow for storage of limited materials for show in the basement as an included benefit as part of this agreement. No storage will be permitted in the lobby or other common areas of the theater. Licensor will handle all ticketing and pay Producer either the total of sold tickets minus the agreed upon rent or the Producers agreed share of sold tickets within 24 hours of the conclusion of each show. If the amount of sold tickets does not cover the agreed upon rental amount then the remainder will be due to the Licensor within 24 hours of completing the event. Producer will adherer to Licensor minimums around ticket pricing. Licensor and Producer will collaborate on marketing endeavors.</div>
    <div><br></div>
    {{services}}
    <div><br></div>
    <div><strong>2. LICENSE; USES OF THE THEATER.</strong></div>
    <div><br></div>
    <div><strong>2.1 GRANT OF LICENSEE.</strong> Subject to the terms and conditions of this Agreement, Licensor hereby grants to Producer, and Producer hereby accepts from Licensor, a limited license to use the Theater solely for the purposes of conducting rehearsals, production, promotion and performances of the Production (the &ldquo;License&rdquo;) during the License Period. As part of the Theater, Licensor shall furnish and make available to Producer, the following: standard venue lighting, audio equipment, microphones, cables, playback devices, and related technical components as designated by Licensor (collectively, the &ldquo;Included Equipment&rdquo;). The Included Equipment shall be identified by venue staff during load-in or technical rehearsal and may be updated or limited at Licensor&rsquo;s discretion based on availability or maintenance. All Included Equipment must be returned in good working condition and reset to venue &ldquo;house&rdquo; settings upon the conclusion of each performance, unless otherwise approved in writing by Licensor.</div>
    <div><br></div>
    <div><strong>2.2 INSPECTION ACCEPTANCE.</strong> Prior to signing this Agreement, Producer has been given the opportunity to inspect the Theater and the Included Equipment and to confirm their suitability and operating condition for supporting rehearsals of the Production. Producer hereby agrees to accept the Theater and the Included Equipment in their present condition, &ldquo;as is&rdquo; and without any further warranty by Licensor whatsoever.</div>
    <div><br></div>
    <div><strong>2.3 USE REQUIREMENTS.</strong> At all times Producer shall use the Theater subject to the review and oversight of Licensor. Producer shall coordinate with Licensor (or its designee) in having access to the Theater and conducting its activities consistently with the License. In furtherance thereof, Producer shall comply with the following:</div>
    <div><br></div>
    <div><strong>2.3.1 ALTERATIONS TO SPACE.</strong> Producer shall not make any interior or exterior improvements, changes, alterations or decorations to or about the Theater, nor shall Producer mark, paint, drill into or in any way deface any part of the Theater or affix any of its settings or property to any surface on the Theater unless Producer first obtains the specific prior written consent of Licensor to each such improvement, change, alteration, decoration or other action and obtains the prior approval, if necessary, of all governmental authorities having jurisdiction thereof. Licensor shall have no responsibility with respect to any improvements, changes, alterations and/or decorations made by Producer, whether or not approved by Licensor.</div>
    <div><br></div>
    <div>The Licensor will not make any alterations to the Mainstage Theatre during the course of the run unless of emergency or due to an act of God.</div>
    <div><br></div>
    <ul>
      <li>A rough floorplan shall be given to the Licensor 4 weeks before tech week.</li>
      <li>Renderings of set design welcome if available</li>
    </ul>
    <div><br></div>
    <div><strong>2.3.2 SCHEDULING CONFLICTS.</strong> Licensor shall retain the exclusive right to resolve any scheduling conflicts or overlapping requests for access to the Theater, including but not limited to rehearsal time, technical load-in, or performance-related activities. Licensor may prioritize access based on prior bookings, operational needs, or technical constraints. Producer acknowledges that use of the Theater is non-exclusive and shall cooperate in good faith with any reasonable adjustments made by Licensor to accommodate multiple users of the space.</div>
    <div><br></div>
    <div><strong>2.4 PRODUCER RESPONSIBILITY.</strong> At all times, whether or not during the License Period, Producer shall be fully responsible for the use of the Theater by any Persons associated with the Production, including any employees or contractors at the Theater on behalf of Producer, any promoter or any other Person responsible for, or related to, the performance of the Production, including all actors, musicians, lighting operators, stage managers, stage hands, customers, technicians, personal assistants or other staff associated with the Production, whether or not employed by Producer. Producer shall not make, and shall not permit, any use of the Theater that is inconsistent with or in conflict with this Agreement. Producer shall repair, at its sole cost and expense, any damage to the Theater or Included Equipment caused by Producer or its employees, agents, contractors or invitees or resulting from Producer&rsquo;s acts or negligence. At the end of the License Period, Producer shall return all light and sound system settings to the original &ldquo;house&rdquo; settings as designated by Licensor.</div>
    <div><br></div>
    <div><strong>2.5 LICENSOR CONTROL: STAFF.</strong> At all times, Producer and all Persons related to the Performance, while present at the Theater, shall be subject to the reasonable direction of the Licensor (or its designee) regarding the manner in which the License is exercised or the Theater used by Producer. Licensor shall be entitled to have a staff member present at the Theater at all times Producer wishes access to the Theater.</div>
    <div><br></div>
    <div><strong>2.6 EXPIRATION.</strong> Following the final performance of the License Period, Producer shall (a) remove from the Theater all equipment (other than the Included Equipment), materials, costumes, set materials, merchandise, and other property related to the Production (and not belonging to Licensor or its contractors); (b) restore the Theater to a &ldquo;broom clean&rdquo; and proper condition; and (c) remove or repair to their original condition any improvements, changes, or damages to the Theater or Included Equipment made by Producer, its contractors, or personnel during the License Period. Producer shall not remove any Included Equipment or any other equipment and personal property belonging or leased to Licensor. Producer is responsible for the prompt removal of all trash, debris, and disposal items related to the Production. If Producer leaves excessive materials, set pieces, or refuse in the Theater that, in Licensor&rsquo;s reasonable discretion, exceeds ordinary post-performance cleanup, Licensor may charge Producer a commercial trash removal fee of up to $250, or the actual cost incurred, whichever is greater. If Producer wishes to utilize Licensor&rsquo;s trash removal service, it must obtain Licensor&rsquo;s prior written consent and shall be responsible for any fees associated with that service. Producer must also comply with the terms of Licensor&rsquo;s disposal or recycling agreements, if applicable. Producer shall cooperate with Licensor in permitting Licensor representatives to supervise the removal of all Production-related property and confirm satisfactory cleanup.</div>
    <div><br></div>
    <div><strong>2.7 SECURITY AND CROWD MANAGEMENT.</strong> Licensor reserves the right, in its sole discretion, to determine whether any scheduled Production activity requires dedicated security, front-of-house, or crowd management personnel based on the nature, size, or timing of the event. If such staffing is required, Producer shall be responsible for providing qualified personnel or, upon Licensor&rsquo;s request, shall reimburse Licensor for the cost of providing such staffing. All security or crowd management personnel must comply with applicable laws and conduct themselves professionally and respectfully while on-site. Licensor may remove or reject any personnel deemed unfit or disruptive. Nothing in this section shall be interpreted as limiting Licensor&rsquo;s ability to staff the venue with its own representatives at any time.</div>
    <div><br></div>
    <div><strong>2.8 DISPOSITION OF PRODUCER PROPERTY.</strong> Following the expiration of the License Period or earlier termination of this Agreement, and subject to Section 3.7 above, Licensor shall be entitled to remove from the Theater any remaining equipment, materials, supplies, property or other materials related to the Production, regardless of value, and deposit such items in a commercial trash removal service.</div>
    <div><br></div>
    <div><strong>2.9 START / END TIMES.</strong> Performances must start within 15 minutes of the scheduled start time. Producer will be given access to space 30 minutes before show start time for load in and set up, earlier accommodations may be made, at Licensor&rsquo;s discretion, for a fee. Performances must conclude within 15 minutes of the scheduled end time. Performances that run over 15 minutes will incur a $100 fee, per performance. Start / end times are noted by the venue representatives.</div>
    <div><br></div>
    <div><strong>2.10 TECH REHEARSAL / REHEARSALS.</strong> Producer is entitled to a single 2 hour technical rehearsal in the space, at the convenience of the venue schedule. Venue technical staff can be onsite to assist with the technical rehearsal for an additional hourly fee of $25/hour. A time extension or a second tech rehearsal may be scheduled at an additional expense. Rehearsal time may be scheduled at a $25/hour fee with a minimum of 2 hours booked for rehearsal. Rehearsals must be booked with 24 hours notice. Rehearsals in both spaces for the same time block would only incur a single rental fee. Rehearsals are not considered open to the public and may not have bar or house management staff available.</div>
    <div><br></div>
    <div><strong>2.11 FIRE.</strong> Live open flame fire may only be used onstage in performances where the Producer presents current, active fire insurance that indemnifies Stars &amp; Garters LLC and it&rsquo;s agents from responsibility for incidents with uncontrolled fire. Producers are responsible for repairing or replacing any fire-damaged equipment or items in the venue. Fire may not be performed in the show without the Producer supplying adequate fire safety and suppression equipment and staff for every live performance.</div>
    <div><br></div>
    <div><strong>3. CONCESSIONS.</strong> Licensor reserves the exclusive right to operate, or contract with concessionaires for, the operation of merchandise, food, and beverage services. Licensor retains 100% of all revenue derived from concessions, including bar sales and merchandise sold by or on behalf of Licensor. Producer shall not sell, distribute, or otherwise offer food, beverages, or alcohol at the Theater without Licensor&rsquo;s prior written consent. Requests by Producer to offer themed or co-branded bar items or merchandise must be submitted in writing for advance approval by Licensor. Any approved co-branded or themed offerings shall be operated by Licensor and all revenues shall remain the sole property of Licensor. Producer staff are eligible for a 20% discount on all bar items. This discount does not extend to guests of the production staff.</div>
    <div><br></div>
    <div><strong>4. DAMAGES TO PRODUCER PROPERTY.</strong> Notwithstanding any other provision of this Agreement, should any property within the Theater that is either owned or leased by Producer be stolen, damaged or destroyed by Persons occupying the Theater with Licensor&rsquo;s express permission (including Licensor personnel or contractors), Licensor shall, subject to any payment due or payable as proceeds from any insurance held by Producer, be responsible for reimbursing to Producer the replacement or repair costs therefore. Producer must deliver prompt notice to Licensor of any such stolen, damaged or destroyed property and, upon Licensor&rsquo;s verification that such loss was not caused by Producer or personnel or contractors subject to Producer&rsquo;s control, Licensor, shall either reimburse the replacement or repair costs directly or take a credit for such costs against any amount (such as the License Fees) otherwise due and payable to Licensor from Producer within the next month. In the event of any dispute regarding the cause of any loss, damage or destruction, Producer shall designate a senior representative who shall cooperate with Licensor in resolving such dispute.</div>
    <div><br></div>
    <div><strong>5. MAINTENANCE OF THEATER.</strong> Licensor shall maintain all parts of the Theater in good, clean, orderly and sanitary condition, with adequate heating or air conditioning, at the beginning of each day of Producer&rsquo;s occupancy during the License Period. Producer shall keep and leave said parts of the Theater in good, clean, orderly and sanitary condition after intermittent use during the day, other than use during regular public performances. Following public performances, Producer shall leave the stage, backstage, lighting booth, and dressing rooms in generally tidy condition. All additional costs or expenses incurred in maintaining the Theater resulting from the building or installing of scenery, machinery, props, etc. on the stage or in the Theater, or relating to the replacement or repair of Included Equipment resulting from Producer&rsquo;s use shall be Producer&rsquo;s liability. Producer acknowledges that no pets or animals (other than service animals) are to be brought in to the Theater, nor shall there be any smoking in the Theater at any time during rehearsals or during the term of this Agreement or any extension thereof except as such activity relates to the performance requirements of the Production (and Producer complies with reasonable safety guidelines established by Licensor for such purposes). No consumption of alcohol is permitted in the Theater or in the immediate vicinity outside the Theater during the term of this Agreement other than via official sales at the bar in the Theater lobby on performance days.</div>
    <div><br></div>
    <div><strong>6. UTILITIES.</strong> Producer agrees that Licensor shall not be liable in damages, by reduction or offset in Weekly License Fees or otherwise, for failure to furnish or delay in furnishing any service, or for any diminution in the quality or quantity thereof, when such failure, delay or diminution is caused, in whole or in part, by repairs, renovations or improvements, by any strike, lockout or other labor trouble, by weather, by inability to secure electricity, gas or other fuel, water, internet or other data connection, or other utility service in the Theater, by any accident or casualty whatsoever, by act or default by Producer or other parties, or by any cause beyond Licensor&rsquo;s reasonable control.</div>
    <div><br></div>
    <div><strong>7. FORCE MAJEURE AND EXCULPATION.</strong> In the event that the Theater is rendered unsuitable, unsafe, or unavailable for presentation of the Production due to fire, flood, earthquake, public health emergency, pandemic, government order, strike, national or local calamity, or any other event or circumstance beyond the reasonable control of either party (each, a &ldquo;Force Majeure Event&rdquo;), the affected party shall provide prompt written notice to the other party, and both Licensor and Producer shall be relieved of their respective obligations under this Agreement for the duration of the Force Majeure Event. Neither party shall be liable to the other for any damages, costs, or losses arising from the suspension or cancellation of performances due to a Force Majeure Event. If the Agreement is terminated due to a Force Majeure Event prior to the first performance date, Licensor shall return to Producer any prepaid rental fees or deposits, less any non-refundable amounts expressly designated in this Agreement or actual expenses incurred by Licensor in reliance on the Production moving forward. If a Force Majeure Event occurs after performances have commenced, any refunds or credits shall be subject to good faith negotiation, taking into account the number of performances completed, actual costs incurred, and the extent of disruption. The failure to settle a fire loss, or delay in recovering insurance proceeds, shall not be deemed negligence so long as Licensor prosecutes any related claim in good faith. Neither party shall be obligated to reschedule or extend the License Period following a Force Majeure Event unless otherwise agreed in writing. In the event of any cancellation or suspension of performances due to a force majeure event as described above, Licensor shall retain any non-refundable deposits previously paid by Producer. Any License Fees or other charges not yet incurred or expressly designated as non-refundable shall be waived or refunded, as appropriate, unless otherwise agreed in writing. Producer acknowledges that Licensor is not responsible for any third-party expenses, lost revenue, or incidental costs resulting from such cancellations.</div>
    <div><br></div>
    <div><strong>8. COMPLIANCE WITH LAW; INDEMNITY.</strong></div>
    <div><br></div>
    <div><strong>8.1 COMPLIANCE WITH LAW.</strong> Producer and Licensor, each for itself, hereby agree to comply in all respects with any and all local, city, state and federal rules, regulations, ordinances, statutes and laws in connection with the use of the Theater. Producer further agrees to commit no act, including the production of any content associated with the Production, which would in any way jeopardize the licenses maintained by Licensor or the reputation of Licensor, and, further, covenants not to commit any act that in any way violates the rules and regulations of the license bureaus of the City of Chicago having jurisdiction over the Theater. Producer further agrees that in producing and performing the Production, Producer shall not violate any copyright, literary or other rights of any Person, including, without limitation, rights of publicity or privacy, nor the terms of any agreement under which Producer has licensed such rights in connection with the Production. For purposes of this Agreement, &ldquo;Person&rdquo; shall mean a natural person, a corporation, a partnership, a limited liability entity, an association, a trust or any other entity or organization, including a government or political subdivision or an agency or instrumentality thereof.</div>
    <div><br></div>
    <div><strong>8.2 INDEMNITY.</strong> To the extent not prohibited by law, Licensor and its managers, members, affiliates, officers, agents and employees shall not be liable for any damage either to person, property or business or resulting from the loss of use thereof sustained by Producer or by other Persons due to the Theater or any part thereof becoming out of repair, or due to the happening of any accident or event in or about the Building, including the Theater, or due to any act or negligence of any licensee, tenant or occupant of the Theater or any other person. This provision shall apply particularly, but not exclusively, to damage caused by gas, electricity, snow, ice, frost, steam sewage, sewer gas or odors, fire, water or by the bursting or leaking of pipes, faucets, sprinklers, plumbing fixtures and windows, and shall apply without distinction as to the person whose act or negligence was responsible for the damage and regardless of cause. Licensor assumes no responsibility for Producer&rsquo;s equipment or other property on or within the Theater in the event of theft or destruction. Producer agrees to indemnify and hold harmless Licensor and its managers, members, affiliates, officers, agents and employees from any and all claims, lawsuits, judgments or damages (including reasonable attorneys&rsquo; fees) (a) arising from any breach by Producer of the covenants, representations, and warranties in this Agreement, including those claims, lawsuits, judgments or damages asserted by third parties arising from any such breach, or (b) arising from the use of the Theater or Building or from any acts or negligence of Producer or its officers, directors, agents, employees, contractors or invitees.</div>
    <div><br></div>
    <div><strong>9. TERMINATION AND LIQUIDATED DAMAGES.</strong></div>
    <div><br></div>
    <div><strong>9.1 INTERPRETATION.</strong> The provisions for termination and liquidated damages provided in this section shall be deemed to be in addition to and not in limitation of other provisions for similar consequences in other portions of this Agreement.</div>
    <div><br></div>
    <div><strong>9.2 TERMINATION FOR NON-PAYMENT.</strong> If Producer fails to timely pay any License Fees or other fee or charge due under this Agreement, Licensor shall provide written notice of non-payment to Producer. If Producer does not cure such non-payment within five (5) business days of receiving notice, Licensor may terminate this Agreement by delivering a second written notice, which shall require the accelerated termination of the Performance Period at the end of the week in which such second notice is delivered. In such event, the Performance Period shall terminate at the end of that week. Compliance with this Section 9.2 shall not limit Licensor&rsquo;s right to suspend the Production or Producer&rsquo;s access to the Theater during any period of non-payment.</div>
    <div><br></div>
    <div><strong>9.3 TERMINATION FOR CAUSE.</strong> In addition to its rights under Section 9.2, Licensor may terminate this Agreement upon written notice if Producer commits a material breach of this Agreement, including but not limited to (a) violation of applicable laws, ordinances, or venue rules; (b) conduct that endangers the health, safety, or welfare of venue staff, guests, or performers; (c) behavior or content that materially damages the reputation or licenses of the venue; or (d) failure to maintain required insurance or provide timely proof thereof. Licensor shall provide Producer with written notice describing the nature of the breach, and if such breach is capable of cure, Producer shall have three (3) business days to cure. If the breach is not cured within such period, or is not curable, Licensor may terminate this Agreement immediately. Upon termination, Producer shall vacate the Theater and remove all Production-related property in accordance with Section 3.6.</div>
    <div><br></div>
    <div><strong>9.4 DAMAGES.</strong> If Producer fails to open the Production, or if Producer closes the Production prematurely through no fault of Licensor, Licensor shall be authorized by Producer to retain all monies paid to it by Producer or otherwise held by Licensor, to the extent of Licensor&rsquo;s actual weekly damages up to and including the amount of Weekly License Fees for four (4) weeks, without prejudice to Licensor&rsquo;s right to demand additional monies due it, whether from the Security Deposit or otherwise; provided, however, that if the Producer&rsquo;s failure to open the Production or Producer&rsquo;s premature closing of the Production results from a disaster, fire, national or local calamity or emergency or any unforeseen occurrence which shall render the fulfillment of this Agreement by the Producer impossible, Producer shall not be held liable for any damages caused thereby, unless caused by the negligence or willful acts of Producer, its agents or employees.</div>
    <div><br></div>
    <div><strong>10. NOTICES.</strong> Any notices under this Agreement, to be effective, shall be in writing and given by personal delivery, sent by certified U.S. Mail, postage prepaid, or by recognized national overnight delivery (such as Federal Express) addressed to the party to be notified at its address set forth in the first paragraph of page 1 of this Agreement. Notices and demands shall be deemed to have been given when mailed or when delivered by recognized national overnight delivery, of, if made by personal delivery, upon such delivery.</div>
    <div><br></div>
    <div><strong>11. MISCELLANEOUS.</strong></div>
    <div><br></div>
    <div><strong>11.1 ROUTINE REPAIRS.</strong> No diminution or abatement of any of the payments or other compensation due from Producer to Licensor hereunder shall be claimed by or allowed to Producer for any inconvenience or discomfort to its business arising from the making of any necessary repairs or alteration to the Theater by Licensor during the term of this Agreement, so long as the seating capacity is not reduced or said Theater is not rendered unusable by Producer for the presentation of the Production.</div>
    <div><br></div>
    <div><strong>11.2 LICENSE: NO AGREEMENT.</strong> This Agreement establishes a license for the non-exclusive use of a theater and the performance of certain services. Nothing contained in this Agreement shall be deemed to create, or otherwise for or constitute, a partnership or landlord-tenant relationship between the parties. Producer shall not assign, delegate or otherwise transfer any license, right or interest granted hereunder or any obligation or covenant undertaken by Producer hereunder, without the prior written consent of Licensor, which may be withheld in Licensor&rsquo;s sole and absolute discretion; any such action on the part of Producer shall be void and of no effect.</div>
    <div><br></div>
    <div><strong>11.3 NO MECHANICS&rsquo; LIENS.</strong> Producer shall not permit any person or entity to file or impose any mechanic&rsquo;s, materialman&rsquo;s, or other lien or encumbrance against the Theater or Building in connection with any work, labor, services, or materials provided at the direction of Producer or its contractors, employees, or agents. If any such lien is filed, Producer shall, within ten (10) days of receiving notice thereof, cause such lien to be discharged of record or bonded over in a manner satisfactory to Licensor, at Producer&rsquo;s sole cost and expense. If Producer fails to discharge or bond over such lien within the required timeframe, Licensor may do so, and Producer shall reimburse Licensor for all reasonable costs and expenses incurred, including attorneys&rsquo; fees and filing fees, within five (5) days of demand.</div>
    <div><br></div>
    <div><strong>11.4 ENTIRE UNDERSTANDING; GOVERNING LAW.</strong> This Agreement, any Exhibits and Schedules hereto attached and any amendments or side letters signed by both parties, contain the entire understanding of the parties. In the event of any conflict between the terms of this Agreement and any Exhibit or Schedule, the terms of the Exhibit or Schedule shall control. There are no representations, warranties, promises, covenants or undertakings other than those herein expressly set forth. No waivers, changes or modifications hereof shall be binding unless in writing and signed by the parties hereto. This Agreement shall be construed and interpreted in accordance with the laws of the State of Illinois.</div>
    <div><br></div>
    <div><strong>11.5 POWER AND AUTHORITY; BINDING AUTHORITY.</strong> If Producer executes this License as a corporation, limited liability company, limited partnership or other entity, Producer, by its execution of this Agreement represents and warrants to Licensor that it has the power and authority to execute this Agreement for and behalf of such entity. Neither party has any authority to bind the other party (and Producer has no authority to bind Licensor) to any agreement with any individual, labor union, society, guild, organization, corporation, or any other third party and each party covenants that it will not so bind the other party or Licensor, as the case may be.</div>
    <div><br></div>
    <div><strong>11.6 EXTENSION OF RIGHTS.</strong> Wherever rights are given to either Producer or Licensor in this Agreement, such rights shall extend to the authorized agents, employees or representatives of such parties.</div>
    <div><br></div>
    <div><strong>11.7 TICKETING.</strong> Within reason the producer may set ticket prices and total ticket quantity for the duration of the rental as well as sell tickets for the event. Comp ticket requests must be submitted no later than 12:00 p.m. on the day of the event. Requests made after 12:00 p.m. must be submitted to the box office staff upon Producer&rsquo;s arrival at the venue and will be subject to availability and venue capacity. Stars &amp; Garters shall be entitled to receive up to four (4) complimentary tickets per live performance for its use or distribution, at no cost to the Licensor. These comped tickets shall not be deducted from Producer&rsquo;s ticket revenue and shall not be resold or reassigned for profit. Licensor may use or transfer these comped tickets at its discretion for guests, marketing, or internal purposes. These comp tickets are in addition to, and not counted against, any guest list or house comps provided by the Producer. Ticketing for the event will be handled by one of the following two methods: If Producer elects to handle their own ticketing, an emailed or printed guest list must be submitted to venue staff by 12:00 p.m. on the day of the performance. At Producer&rsquo;s request, ticketing will be managed by Stars &amp; Garters. Pricing, dates, times, and a show synopsis must be submitted no later than three (3) months prior to opening night to ensure timely event creation and promotional updates. Requested changes must be submitted with at least three (3) business days&rsquo; notice. Net ticket revenue, minus applicable fees and expenses, will be paid to the Producer by check within seven (7) days of Strike.</div>
    <div><br></div>
    <div><strong>11.8 MARKETING.</strong> Producer may provide up to four (4) 11&quot; x 17&quot; posters to be hung by venue staff in the lobby and public areas of the venue. Producer may also provide a vertical electronic poster to be displayed in rotation on the venue&rsquo;s digital screens (1280 x 720 / 300 dpi). Licensor may also grant the Producer a 24&quot; x 36&quot; poster frame space in the central lobby, subject to availability. Producer may elect to leave printed postcards for the Production in the designated promotional area of the lobby. The Production will also be included in venue social media and marketing, in Licensor&rsquo;s sole discretion. Producer shall not use the name &ldquo;Stars &amp; Garters,&rdquo; the venue logo, any photographs of the venue interior or exterior, or any likeness thereof in any press release, public announcement, or marketing material without Licensor&rsquo;s prior written approval. Licensor reserves the right to revoke such approval if any use is deemed misleading, reputationally harmful, or inconsistent with the venue&rsquo;s branding. Licensor shall not unreasonably withhold approval for factual use of the venue name and location in show listings or event calendars.</div>
    <div><br></div>
    <div><strong>11.9 DISPUTE RESOLUTION; GOVERNING LAW; VENUE.</strong> This Agreement shall be governed by and construed in accordance with the laws of the State of Illinois, without regard to its conflict of law principles. In the event of any dispute arising out of or relating to this Agreement, the parties agree to first attempt to resolve the dispute in good faith through informal discussions. If the dispute cannot be resolved informally, either party may submit the dispute to non-binding mediation in Cook County, Illinois. If the parties are unable to resolve the dispute through mediation, either party may bring an action in a court of competent jurisdiction located in Cook County, Illinois, and each party consents to the exclusive jurisdiction and venue of such courts. Each party waives any objection to venue or jurisdiction on the grounds of forum non conveniens.</div>
    <div><br></div>
    <div><strong>11.10 ADA AND ACCESSIBILITY COMPLIANCE.</strong> Licensor represents that the Theater complies with applicable federal, state, and local accessibility requirements for public accommodations. Producer shall be responsible for ensuring that its Production, including any sets, casting, interactive features, or audience engagement, complies with the Americans with Disabilities Act (ADA) and all other applicable accessibility laws. Producer agrees to indemnify and hold harmless Licensor from any claim, penalty, or liability arising from Producer&rsquo;s failure to comply with such obligations.</div>
    <div><br></div>
    <div><strong>11.11 INTELLECTUAL PROPERTY AND LICENSING.</strong> Licensor makes no claims on producers intellectual property rights. Producer shall be solely responsible for obtaining, at its own expense, all rights, licenses, consents, and clearances necessary for the use and performance of any copyrighted materials, including but not limited to musical works, scripts, video content, trademarks, and images incorporated into the Production. Producer represents and warrants that it has secured such permissions and agrees to indemnify and hold harmless Licensor from and against any and all claims, damages, liabilities, costs, or expenses (including attorneys&rsquo; fees) arising from any alleged or actual infringement of third-party intellectual property rights in connection with the Production.</div>
  HTML
end
